### ISSUE TITLE
Create feat to publish test (cannot allow editing + allow answers)

### ISSUE THREAD

**Issue by KarinePistili** [uramakilab/remote-usability-lab#106]
1. Create feature to PUBLISH test
2. When published it be cannot edited
3. Users can answer only if it IS PUBLISHED

**Comment by TalesAugusto1** [comment]
Add a field in the firestore (something like "isPublished") that is a boolean. If true, the edit test page must be disabled; if false, the save btn for answering the test should be disabled instead.
