### ISSUE TITLE
Review the old branch previewTest

### ISSUE THREAD

**Issue by TalesAugusto1** [uramakilab/remote-usability-lab#139]
Check if the test creation/edition works on user tests.

**Comment by Na1au** [comment]
Branch testPreview: 

> It works until the [Update ScreenButton](https://github.com/uramakilab/remote-usability-lab/commit/a38fd905bd1aef1b1804018cc4bd3ea94d869115) commit, after that the user test codes are lost

Bugs: 
- When you edit a task, the system duplicate it
- Pre test and post test redirrect to a 'File excluded' view on Google Drive
- Reports view show a loading that never stops
- Answers and analytics views are empty (just a white background), even after an answer was submitted
- The camera, audio, timer and screen record don't stop after submitting the answer
- The answer don't save on the store or on firebase, so all the progress is losted
- The UI is really bad, that 
- The recoreds aren't saved on the storage or in the store, they are just BLOB files

Files that we can use: 
- ViewTask.vue (settings about the tasks)
- TipButton.vue
- AudioButton.vue
- CameraButton.vue
- ScreenButton.view
