### ISSUE TITLE
Field Study: Remote tests

### ISSUE THREAD

**Issue by TalesAugusto1** [uramakilab/remote-usability-lab#140]
Do a bibliographyc research on remote tests tools.

The top 10 remote user testing tools in 2023

- [x] Userbrain.
- [x] UserTesting.
- [x] Lookback.
- [x] Maze.
- [x] Userzoom.
- [x] Testbirds.
- [x] Hotjar.
- [x] Loop11.
"

Acording to google.

Research focus: 

> How those tools analise the test.
> Wich kind of questions it has.
> How the result is analyzed there.

**Comment by TalesAugusto1** [comment]
Mesa has a very simple way to handle user tests with a atractive and simple interface for the user.
When creating a "Maze", the admin faces options that he may use to generate his user test, such as adding images, select the way and kind of question, adding notes and creating a condition for that specific question.

![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/c3e9b615-a742-43f8-a22a-f54d895b3406)[

That way, the user creates his test using blooks (making the whole process of generating a test very simple)

![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/8ccbeffd-cc7a-4df1-a240-ed3778a195af)


one of the most interesting features of Mase is the possibility to add a prototype in figma for tests:

![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/6f76b744-47b1-49d1-b987-c5f77430e42f)

It is possible to visualize the test before sharing with users:

![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/31a9d7af-b16b-450e-90c0-5b5eb70d13d4)


the managment of tests page is simple and clean:
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/b06a72d4-c093-4439-bbb9-1f2e9506edbc)

So is the answers page:
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/c151f0d8-7710-4585-be9a-31d2b6a0808b)
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/b707a9af-71c0-46f8-8b76-e3d5e553d936)
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/ba7fc32d-4dc7-4a58-89b0-4da8a13bbfa7)
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/22ad1870-74c9-41a8-b073-3e559c49765c)

**Comment by jvJUCA** [comment]
The design of Userbrain is simple and aesthetic, when you will create a test you have 3 options:
![Captura de ecrã de 2023-09-21 17-54-21](https://github.com/uramakilab/remote-usability-lab/assets/128351990/22e36ded-1434-4b37-9c83-ba2bac5a3bb0)
You can add instructions for testers
![Captura de ecrã de 2023-09-21 18-03-51](https://github.com/uramakilab/remote-usability-lab/assets/128351990/77533657-9c3c-4cfc-9b56-2278fc992b50)
The tasks response has options to be a rating, writing response, task, multiple choice, single choice, redirect, i like this options for each task, you can choose the device of the users who will tests.
![Captura de ecrã de 2023-09-22 11-19-48](https://github.com/uramakilab/remote-usability-lab/assets/128351990/b4ec89ef-56fe-40f7-935f-e38937a24fdd)
You can choose the number, the price for testers is relative to number of testers.
![Captura de ecrã de 2023-09-22 11-21-14](https://github.com/uramakilab/remote-usability-lab/assets/128351990/24e45684-d59f-4374-88ab-30102870b141)
![Captura de ecrã de 2023-09-22 11-27-36](https://github.com/uramakilab/remote-usability-lab/assets/128351990/b0ee7bbd-5243-4b88-ba7f-0e3425cea30b)
In UserBrain, testers are paid to test applications, and usability tests are tailored to the chosen profile. The creators of the tests pay testers to use their application. In my opinion, it is quite expensive to use, but it offers many features.

**Comment by TalesAugusto1** [comment]
Hotjar is a User Test tool with its focus on traking the "thoughts" of the user while using your application by creating a hotmap of the user eyes over different screens. One application flaw is it's need to be downloaded for use.

![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/f0c66272-1dfc-4298-9d1c-0176b0fbcf72)

Other bad thing would be the need of updating your code to use this tool.
On the other hand, the test admin is able to track the clicks, mouse move and scroll of individual pages at his application, where it has been acessed (notebook, tablet, smartphones) and how much access in each individual device.
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/0595cf22-367b-46b9-813e-6391d725df16)

Scroll example:
![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/f836b885-f1b7-4566-bbcc-a668cd4eccfc)

![image](https://github.com/uramakilab/remote-usability-lab/assets/104631043/bad34f18-4080-4819-b077-e373b95a2ba2)
There is the possibility to record the screen of the user while using your website, this allows evaluators to better interpretate the user

**Comment by jvJUCA** [comment]
- Lookback has a simple and minimalist design, with too much options for tests and i signed with free trial of 5 days.


![Image](https://github.com/uramakilab/remote-usability-lab/assets/128351990/52a054ae-f907-4b8d-9f31-2822d0ec6393)


- In Lookback you can choose if your usability test is a Interview, live share, Self test and Tasks.


![Image](https://github.com/uramakilab/remote-usability-lab/assets/128351990/57f4f96e-f33e-471f-a628-e6b55351057e)

- The User who want to people tests their applications with Task or self test option can make a test with Device requirements, if the tester camera is optional, required, or disabled in the test, you can choose if the tasks options is ramdomized or no, and choose the number of sessions the collaborator can open.


![Image](https://github.com/uramakilab/remote-usability-lab/assets/128351990/4f2bc3a1-e864-4788-b9ae-86af63e2a2a0)


- With you choose interview method the application just give the path for your video call


![Image](https://github.com/uramakilab/remote-usability-lab/assets/128351990/7110897d-00e0-47d5-92bd-bbb80655152d)

- Here you have the page of the sessions, is organized by Session name, Duration, Creation date, Device, Notes and Highlights.


![Image](https://github.com/uramakilab/remote-usability-lab/assets/128351990/dde75b8c-d9d8-4056-b055-f655b61ea161)


- Here is the prices of the plans to make your tests


![Image](https://github.com/uramakilab/remote-usability-lab/assets/128351990/f60ddc30-95e8-4336-a16c-d8c2d2d100f6)
