### ISSUE TITLE
Create Template Not Updating Nav Bar

### ISSUE THREAD

**Issue by leoruas** [uramakilab/remote-usability-lab#15]
Whenever you create a template in your test the tabs in the navigation bar should update to show the template tab

**Comment by KarinePistili** [comment]
We can create templates from tests by going to their config tab.

![image](https://user-images.githubusercontent.com/43211581/154688920-7dea7255-896d-489b-98be-92fd06fcc0ee.png)

When we hit create, the template is correctly created and user is redirected to the main dashboard. But what happens is that the test does not appear in the list of templates. The template only appears if we hit refresh
