### ISSUE TITLE
Heuristic Test Editing Index Bug

### ISSUE THREAD

**Issue by leoruas** [uramakilab/remote-usability-lab#2]
When editing heuristics and questions in a test with an unusual workflow, the questions start appearing in the wrong heuristic.

Probably something to do with the way questions are indexed in EditTestView.vue

**Comment by KarinePistili** [comment]
Error reproduced in the video https://drive.google.com/file/d/128Bh4nTCSjZ4GmQyhNaGtADTR1llyzmb/view?usp=sharing
